name: Deploy to GitHub Pages
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir -p public
          cp -r frontend/* public/
          touch public/.nojekyll  # Важно!

      - name: Deploy
        uses: actions/deploy-pages@v2