name: Deploy to GitHub Pages
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          mkdir -p public
          cp -r frontend/* public/
          touch public/.nojekyll

      - name: Deploy
        run: |
          cd public
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy $(date +'%Y-%m-%d %H:%M:%S')"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push -f origin gh-pages