name: Deploy to GitHub Pages
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir -p public
          cp -r frontend/* public/
          touch public/.nojekyll

      - name: Direct Deploy
        run: |
          cd public
          git init
          git checkout -b gh-pages  # Явно создаем нужную ветку
          git add .
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Deploy to GitHub Pages"
          git push -f https://${{ github.token }}@github.com/${{ github.repository }}.git gh-pages